# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d317c2e44068ba3dfd306760cdf871323327aad2601a84daea60d3d7a2b8be6d1689db19affe08f9a36926683af373fb1ef0ac1d2f7253c9e1a5a23e156f61e

test:
  secret_key_base: e39ea7dd4c9fcf5f5825bf9e9c94a6ba7e4b5a3b2572faf382717cf01ce43855bcc243bc213738c07cbbeb5bfa22b3f9912aa0c5da3ec528d9ea9c8c6a70f8f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
